# frozen_string_literal: true
#
# Issue: rsim/oracle-enhanced#2383
# Title: Enum name query doesn't work with char type
# URL: https://github.com/rsim/oracle-enhanced/issues/2383
# Status: reproduced
# Notes:
#   Reporter declares `enum status: { active: '0', archived: '1' }` on a model
#   whose `status` column is `CHAR(1)`. After `Post.create!(status: :archived)`,
#   `post.archived?` returns false even though the row was written correctly.
#
#   I initially suspected this was Oracle's blank-padding of CHAR(n) values
#   leaking through to the AR layer (e.g. CHAR(3) storing '1' as '1  '). The
#   Oracle Enhanced adapter actually handles that: short CHAR reads come back
#   trimmed (CHAR(3) of 'A' returns "A" not "A  "). The padding hypothesis
#   does NOT explain the bug.
#
#   The real root cause is on the AR side, in how the enum subtype interacts
#   with Oracle Enhanced's `CharacterString::Data` value wrapper:
#
#     post.status                              => "archived"  (looks fine)
#     post.archived?                           => false        BUG (should be true)
#     post.send(:_read_attribute, :status)     => nil          this is why
#     post.read_attribute(:status)             => "archived"
#
#   AR's `archived?` predicate is generated by `ActiveRecord::Enum` and
#   delegates to `_read_attribute(:status) == "archived"`. When the column
#   value is stored internally as Oracle Enhanced's
#   `ActiveRecord::Type::OracleEnhanced::CharacterString::Data` wrapper, the
#   enum subtype's `cast`/`deserialize` chain returns nil from
#   `_read_attribute`, so the predicate is always false.
#
#   The SQL-level scopes generated by enum (e.g. `Post.archived`) DO work --
#   they bind the raw enum value `'1'` into the WHERE clause, and Oracle
#   returns the matching row. So the bug is strictly in the per-instance
#   predicate / `_read_attribute` path, not in query generation.

require "spec_helper"

RSpec.describe "Issue #2383: Enum name query doesn't work with char type" do
  include SchemaSpecHelper

  before(:all) do
    ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
    schema_define do
      # NB: id: false matches the issue's reproduction. The auto-id is
      # irrelevant to the bug (we never reload here), and `id: false` keeps
      # the schema as close to the reporter's snippet as possible.
      create_table :test_issue_2383_posts, force: true, id: false do |t|
        t.column :status, "CHAR(1)"
      end
    end

    class ::TestIssue2383Post < ActiveRecord::Base
      self.table_name = "test_issue_2383_posts"
      # The issue's verbatim form is `enum status: { active: '0', archived: '1' }`
      # (AR <= 7.0 keyword API). AR 7.1+ requires the positional form. The
      # bug being demonstrated is orthogonal to which DSL spelling is used.
      enum :status, { active: "0", archived: "1" }
    end
  end

  after(:all) do
    Object.send(:remove_const, "TestIssue2383Post") if defined?(TestIssue2383Post)
    ActiveRecord::Base.lease_connection.drop_table :test_issue_2383_posts, if_exists: true
    ActiveRecord::Base.clear_cache!
  end

  before(:each) do
    TestIssue2383Post.delete_all
  end

  it "writes the row with the raw enum value (sanity)" do
    TestIssue2383Post.create!(status: :archived)
    raw = ActiveRecord::Base.lease_connection.select_value(
      "SELECT status FROM test_issue_2383_posts WHERE ROWNUM = 1"
    )
    expect(raw).to eq("1")
  end

  it "exposes the enum name via the reader (sanity)" do
    post = TestIssue2383Post.create!(status: :archived)
    expect(post.status).to eq("archived")
    expect(post.read_attribute(:status)).to eq("archived")
  end

  it "the enum predicate returns the wrong answer [BUG #2383]" do
    post = TestIssue2383Post.create!(status: :archived)

    # The user-facing reader agrees the status IS 'archived' ...
    expect(post.status).to eq("archived")

    # ... but the enum-generated predicate disagrees. This is the headline
    # symptom from the issue: "post#archived? returns false". With the bug
    # present, this assertion fails.
    expect(post.archived?).to be true
  end

  it "documents that _read_attribute returns nil [root cause #2383]" do
    # AR's `archived?` predicate is defined as `_read_attribute(name) == "archived"`.
    # On CRuby + ruby-oci8 + oracle_enhanced, the CharacterString::Data wrapper
    # makes `_read_attribute(:status)` return nil even though `read_attribute`
    # (public) returns "archived". That mismatch is why the predicate is false.
    post = TestIssue2383Post.create!(status: :archived)
    expect(post.send(:_read_attribute, :status)).to eq("archived")
  end

  it "SQL-level enum scope still works (the bug is per-instance only)" do
    TestIssue2383Post.create!(status: :archived)
    TestIssue2383Post.create!(status: :active)

    # The SQL generated by `TestIssue2383Post.archived` binds the raw value
    # '1' in the WHERE clause and Oracle returns the matching row correctly.
    expect(TestIssue2383Post.archived.count).to eq(1)
    expect(TestIssue2383Post.where(status: :archived).count).to eq(1)
  end
end
