# frozen_string_literal: true
#
# Issue: rsim/oracle-enhanced#2049
# Title: How to create records into table with generated 'as identity' primary key?
# URL: https://github.com/rsim/oracle-enhanced/issues/2049
# Status: FIXED on master (8.0.x line) -- repro does NOT reproduce.
# Notes:
#   User scenario (Oracle 12c+, oracle-enhanced 6.0.4, AR 6.0):
#     A table is created OUTSIDE ActiveRecord via raw DDL with
#     `text_file_id NUMBER(12) GENERATED ALWAYS AS IDENTITY PRIMARY KEY`
#     and a non-id primary key column. The AR model sets `self.primary_key`
#     but does NOT call `create_table identity: true` (because the table
#     wasn't created through the migration DSL). On 6.0.4, `.create!`
#     delegated to oracle-enhanced's prefetch path, which guessed a sequence
#     name `T_TEXT_FILE_SEQ` and ran
#       SELECT "T_TEXT_FILE_SEQ".NEXTVAL FROM dual
#     -> ORA-02289: sequence does not exist.
#
#     The reporter also tried `self.sequence_name = :autogenerated`, which
#     used to disable prefetch on older versions but now raises
#     "Trigger based primary key is not supported".
#
#   On current master this repro PASSES, both tests:
#     1. `create!` populates `text_file_id` with the identity-generated
#        value and the row is round-trippable via `.find`.
#     2. `prefetch_primary_key?("t_text_file")` returns false, so AR does
#        not attempt to fetch from a guessed sequence.
#
#   The adapter now consults `user_tab_identity_cols` to detect identity
#   columns at runtime (see lib/active_record/connection_adapters/
#   oracle_enhanced/schema_statements.rb and the `identity_primary_key_spec`
#   coverage), so raw-DDL identity tables work even without going through
#   `create_table identity: true`. The issue can be closed as fixed.

require "spec_helper"

RSpec.describe "Issue #2049: identity primary key created via raw DDL" do
  before(:all) do
    ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
    @conn = ActiveRecord::Base.lease_connection

    skip "requires Oracle 12.1+ (GENERATED AS IDENTITY)" unless @conn.database_version >= "12"

    # Mirror the user's DDL exactly: table created with raw SQL, NOT via
    # `schema_define { create_table :t_text_file, identity: true }`. The
    # primary key is `text_file_id`, not `id`.
    @conn.execute "DROP TABLE t_text_file" rescue nil
    @conn.execute <<~SQL
      create table t_text_file
      (
          text_file_id number(12) generated always as identity
              constraint t_text_file_pk
                  primary key,
          name         varchar2(20),
          data         clob
      )
    SQL

    # The model definition is exactly what the user posted.
    class ::TestIssue2049TextFile < ActiveRecord::Base
      self.table_name = "t_text_file"
      self.primary_key = "text_file_id"
    end
  end

  after(:all) do
    Object.send(:remove_const, "TestIssue2049TextFile") if defined?(TestIssue2049TextFile)
    @conn = ActiveRecord::Base.lease_connection
    @conn.execute "DROP TABLE t_text_file" rescue nil
    ActiveRecord::Base.clear_cache!
    @conn.schema_cache.clear! if @conn.respond_to?(:schema_cache)
  end

  it "create! succeeds and populates the auto-generated primary key" do
    # The user calls .create (not .create!) but .create! makes the failure
    # mode loud here instead of silently returning an invalid record.
    row = TestIssue2049TextFile.create!(name: "file.csv", data: "line1\nline2")

    expect(row.text_file_id).to be_a(Integer)
    expect(row.text_file_id).to be > 0
    expect(row.persisted?).to be true

    # Round-trip: the row should be findable by its generated id.
    reloaded = TestIssue2049TextFile.find(row.text_file_id)
    expect(reloaded.name).to eq("file.csv")
    expect(reloaded.data).to eq("line1\nline2")
  end

  it "does not try to fetch from a guessed sequence T_TEXT_FILE_SEQ" do
    # If the bug is live, this query runs and raises ORA-02289 because
    # the sequence does not exist (the column is identity-backed).
    expect(@conn.prefetch_primary_key?("t_text_file")).to be false
  end
end
