# frozen_string_literal: true
#
# Reproduction for rsim/oracle-enhanced#2147
# Title:  "Wrong time returned for timestamptz with :local default_timezone around DST time change"
# URL:    https://github.com/rsim/oracle-enhanced/issues/2147
# Reporter: ioev (2021-02-10), revived by toffeegryphon
# Reported against: Rails 6.0 / oracle-enhanced 6.0.6 / Ruby 2.7.2 / Oracle 12.2
#
# Summary of the report:
#   When a column is declared `TIMESTAMP WITH TIME ZONE` and the adapter is
#   configured with `ActiveRecord.default_timezone = :local`, a Time value
#   that falls inside a DST-fall-back transition window comes back from the
#   database offset by one hour. The reporter pinpointed the offending code
#   in `oci_connection.rb#typecast_result_value` (now around
#   `create_time_with_default_timezone`), which reconstructs the Time from
#   its (year, month, day, hour, min, sec) components using
#   `Time.send(:local, ...)`. That call drops the original UTC offset
#   carried on the TIMESTAMPTZ value and resolves the ambiguous local time
#   (1:30am on the fall-back date occurs twice) to whichever instant Time#local
#   picks. The two instants are exactly one hour apart, hence the one-hour
#   offset the reporter observed.
#
#   See lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb
#   (def create_time_with_default_timezone) — the `Time.send(ActiveRecord.default_timezone, ...)`
#   path is the exact site the issue points at.
#
# Expected: a round-tripped Time equals the inserted Time (same instant).
# Actual (per report and reproduced here): the round-tripped Time is offset
#   by one hour, because the offset/zone information from the TIMESTAMPTZ
#   value is discarded when ruby reassembles a local Time from components.
#
# Status (on master @ e8e1677c, Rails 8.2.0.alpha, Ruby 4.0.1, Oracle 21c XE,
# ruby-oci8): REPRODUCES. Fall-back ambiguous-hour values round-trip with the
# wrong instant when ActiveRecord.default_timezone = :local and ENV["TZ"]
# names a DST-observing zone. Spring-forward instants outside the gap are
# also round-tripped via the same lossy `Time.local(...)` path; the assertion
# below additionally pins the spring-forward case as a sanity check.

require "spec_helper"

RSpec.describe "Issue rsim/oracle-enhanced#2147: timestamptz round-trip drops offset under :local default_timezone" do
  # America/New_York fall-back 2021: at 02:00 EDT clocks rewind to 01:00 EST.
  # 01:30 local time exists twice on 2021-11-07 — once at -04:00 (EDT) and
  # once at -05:00 (EST). The bug surfaces when we insert the *first* (EDT,
  # -04:00) instant and the adapter returns the *second* (EST, -05:00)
  # instant — a one-hour drift.
  DST_TZ = "America/New_York"

  before(:all) do
    @original_tz = ENV["TZ"]
    ENV["TZ"] = DST_TZ
    @original_default_timezone = ActiveRecord.default_timezone
    ActiveRecord.default_timezone = :local

    ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
    @conn = ActiveRecord::Base.lease_connection
    @conn.execute "DROP TABLE issue_2147_posts" rescue nil
    @conn.execute <<~SQL
      CREATE TABLE issue_2147_posts (
        id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        posted_at   TIMESTAMP WITH TIME ZONE
      )
    SQL
  end

  after(:all) do
    @conn.execute "DROP TABLE issue_2147_posts" rescue nil
    ActiveRecord.default_timezone = @original_default_timezone
    if @original_tz.nil?
      ENV.delete("TZ")
    else
      ENV["TZ"] = @original_tz
    end
  end

  before(:each) do
    stub_const("Issue2147Post", Class.new(ActiveRecord::Base) do
      self.table_name = "issue_2147_posts"
    end)
    Issue2147Post.delete_all
  end

  it "round-trips a TIMESTAMPTZ value that lies inside the DST fall-back ambiguity window" do
    # 01:30 EDT (-04:00) on the fall-back date. Thirty minutes before the
    # rewind. The corresponding 01:30 EST (-05:00) instant is one hour later.
    time = ::Time.new(2021, 11, 7, 1, 30, 0, "-04:00")

    post = Issue2147Post.create!(posted_at: time)
    post.reload

    # Same instant in time, regardless of which local-time representation
    # the adapter or the DB chose to hand back. Comparing with `==` on Time
    # compares the underlying instant, so this is the strictest correctness
    # assertion: "no hour was lost in transit."
    expect(post.posted_at.to_i).to eq(time.to_i),
      "TIMESTAMPTZ round-trip drifted across the DST boundary. " \
      "Inserted #{time.iso8601} (#{time.to_i}); got back " \
      "#{post.posted_at.iso8601} (#{post.posted_at.to_i}). " \
      "Delta = #{post.posted_at.to_i - time.to_i}s. " \
      "See create_time_with_default_timezone in oci_connection.rb — the " \
      "Time.send(:local, year, month, day, hour, min, sec, usec) call " \
      "drops the source offset and resolves ambiguous local times to the " \
      "post-fall-back instant."
  end

  it "round-trips a TIMESTAMPTZ value just before the DST spring-forward gap (control)" do
    # 01:30 EST (-05:00) on the spring-forward date. Unambiguous local time
    # (the 02:00-03:00 wall-clock hour does not exist on 2021-03-14), so
    # this should round-trip even with the lossy reconstruction. Acts as a
    # negative control: if this ALSO fails, the bug is broader than DST
    # ambiguity and the diagnosis above is wrong.
    time = ::Time.new(2021, 3, 14, 1, 30, 0, "-05:00")

    post = Issue2147Post.create!(posted_at: time)
    post.reload

    expect(post.posted_at.to_i).to eq(time.to_i),
      "Even the unambiguous pre-spring-forward instant did not round-trip. " \
      "Inserted #{time.iso8601}; got back #{post.posted_at.iso8601}."
  end
end
